version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: parbak_db
    environment:
      POSTGRES_USER: b2b
      POSTGRES_PASSWORD: b2b123
      POSTGRES_DB: b2b
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: parbak_redis
    ports:
      - "6379:6379"

  opensearch:
    image: opensearchproject/opensearch:2.19.1
    container_name: parbak_os
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_JAVA_OPTS=-Xms256m -Xmx256m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=ParBak1369
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"

volumes:
  db-data: {}
